version: '3.8'
services:
  db:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: "toor"
    expose:
      - '3306'
    volumes:
        - supermarketspringapp:/var/lib/mysql
  volumes:
    supermarketspringapp:



